### ISSUE TITLE
Should non-members have access to social features in 'open' workspaces?

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#884]
Open workspaces currently allow non-members to read all published content, but not to post updates or comments. @bfackland suggests that they should be able to access these social features as well.

Under the original concept, the idea was that open workspaces could also allow self-joining. If a user self-joined a workspace, they would then get access to all social/notification functionality.

At the moment there is no self-joining UI that I'm aware of, so raising this for discussion

/cc @gyst

**Comment by gyst** [comment]
What you're highlighting is that the permissions for a member-Consumer (read+interact) are not the same as for a global-Reader (read).

The proper fix for that is indeed to enable self-join, not to increase Reader permissions. We have that in the backend (I think?) but need a front-end design for that. Can be as simple as a button 'Become a member of this group to start interacting' prominently on the stream page.

However, once we have that button, only for "self-managed" spaces, we also need the corresponding "Leave this group" button, and not only for "self-managed" but also for "team-managed" spaces. This button rightfully belongs in the membership management pane, but that would be inconsistent with the self-join button placement, which ought not to be hidden in the membership management pane. Hence, we need design.

## Todo:
- [ ] open prototype ticket
- [ ] design proper solution for both self-join and self-leave
- [ ] get OK from @cornae :-) = merge proto pull request
- [ ] implement
- [ ] add robot tests and any missing backend functionality
